name = "webproxy"
main = "worker/src/index.ts"
compatibility_date = "2026-08-18"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./client/dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "COOKIE_JAR"
class_name = "CookieJar"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CookieJar"]

[[kv_namespaces]]
binding = "USER_DATA"
id = "fbe05d6ecd5b47668ea0b8ca95399fed"